package test.test1;
// Generated Dec 5, 2016 12:24:52 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Store generated by hbm2java
 */
@Entity
@Table(name="store"
    ,schema="public"
)
public class Store  implements java.io.Serializable {


     private int id;

    public Store() {
    }

    public Store(int id) {
       this.id = id;
    }
   
     @Id 
    
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }




}


